import {Food} from './app/shared/models/Foods';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        price: 8,
        cookTime: '30-40',
        favorite: true,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-1.jpg',
        tage: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 10,
        cookTime: '30-40',
        favorite: false,
        origins: ['Persia middle east china'],
        stars: 3.0,
        imageUrl: 'assets/food-2.jpg',
        tage: ['Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 9,
        cookTime: '30-40',
        favorite: true,
        origins: ['germany us'],
        stars: 4.5,
        imageUrl: 'assets/food-3.jpg',
        tage: ['FastFood', 'Lunch', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 12,
        cookTime: '40-50',
        favorite: true,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-4.jpg',
        tage: ['FastFood', 'Fry', 'Lunch'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 15,
        cookTime: '45-60',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tage: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '30-40',
        favorite: true,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tage: ['FastFood', 'Pizza', 'Lunch'],
    },
]

export const sample_tags:Tag[] = [
    {name: 'All', count: 6},
    {name: 'FastFood', count: 4},
    {name: 'Pizza', count: 2},
    {name: 'Lunch', count: 3},
    {name: 'SlowFood', count: 2},
    {name: 'Hamburger', count: 1},
    {name: 'Fry', count: 1},
    {name: 'Soup', count: 1},
]